### ISSUE TITLE
Edit profile 

### ISSUE THREAD

**Issue by shihabshaharia** [Simply-Nikah/simply-nikah-issues#5]
![Screenshot_20240424_192802_Simply Nikah](https://github.com/Simply-Nikah/simply-nikah-issues/assets/70126191/3b8d2e1b-db0c-4c8c-aca7-5cc2911be6d9)

There's no save button in this screen. So feels a bit confusing. Also the images that I added earlier are gone. But profile picture is is saved.

**Comment by YoussefLasheen** [comment]
Not adding a save button is intended. Please open another issue for anything else.
